version: 2.1

android_config: &android_config
  docker:
    - image: gmemstr/flutter-fastlane:latest
  environment:
    TERM: dumb
    _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  beta_deploy:
    <<: *android_config
    steps:
      - checkout
      - run: cd android
      - run: fastlane android beta_deploy

workflows:
  deploy:
    jobs:
      - beta_deploy:
          filters:
            branches:
              - beta