version: 2.1

android_config: &android_config
  docker:
    - image: gmemstr/flutter-fastlane:latest
  environment:
    TERM: dumb
    _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  beta_deploy:
    <<: *android_config
    steps:
      - checkout
      - run: sudo mkdir -p /home/gsimmer && sudo chown cirrus /home/gsimmer
      - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > /home/gsimmer/key.jks
      - run: touch project/android/key.properties
      - run: echo "$PLAY_STORE_UPLOAD_KEY_INFO" | base64 --decode > android/key.properties
      - run: cd android
      - run: fastlane android beta_deploy

workflows:
  deploy:
    jobs:
      - beta_deploy:
          filters:
            branches:
              only: beta