# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_number(
          bump_type: "minor"
    )
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new beta build to Google Play"
  lane :beta_deploy do
    # Return the number of commits in current git branch
    puts Dir.pwd
    build_number = number_of_commits()
    Dir.chdir "../.." do
      puts Dir.pwd
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end
    upload_to_play_store(track: 'beta', aab: '../build/app/outputs/bundle/release/app.aab')
  end

end
